"""add score breakdown columns

Revision ID: 371e359fdbbe
Revises: 3f6ad6ff4f80
Create Date: 2026-07-05 10:59:03.120050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371e359fdbbe'
down_revision: Union[str, Sequence[str], None] = '3f6ad6ff4f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ats_analyses', sa.Column('keyword_score', sa.Integer(), nullable=True))
    op.add_column('ats_analyses', sa.Column('structure_score', sa.Integer(), nullable=True))
    op.add_column('ats_analyses', sa.Column('skills_score', sa.Integer(), nullable=True))
    op.add_column('ats_analyses', sa.Column('ai_review_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ats_analyses', 'ai_review_score')
    op.drop_column('ats_analyses', 'skills_score')
    op.drop_column('ats_analyses', 'structure_score')
    op.drop_column('ats_analyses', 'keyword_score')
    # ### end Alembic commands ###
